name: my-chart
description: A Helm chart for deploying simple workloads Kubernetes
annotations:
  title: my-chart
type: application
version: "0.1.5"
apiVersion: v2
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: delichik
    url: https://github.com/delichik/my-charts
    email: delichik@imiku.moe
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://www.truenas.com/
icon: https://media.sys.truenas.net/apps/ix-chart/icons/icon.webp
keywords: []
sources: []
