name: my-chart
description: A Helm chart for deploying simple workloads Kubernetes
annotations:
  title: my-chart
type: application
version: "0.1.4"
apiVersion: v2
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://www.truenas.com/
icon: https://media.sys.truenas.net/apps/ix-chart/icons/icon.webp
keywords: []
sources: []
