{{- if and (.Values.portForwardingList) (eq (include "hostNetworkingConfiguration" .) "false") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ix-chart.fullname" . }}
  labels:
    {{- include "ix-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType | quote }}
  ports:
{{- if eq .Values.serviceType "NodePort" }}
    {{- range $index, $config := .Values.portForwardingList }}
    - port: {{ $config.containerPort }}
      targetPort: {{ $config.containerPort }}
      protocol: {{ $config.protocol }}
      nodePort: {{ $config.nodePort }}
      name: ix-{{ $.Release.Name }}-{{ $config.nodePort }}-{{ $index }}
    {{- end }}
{{ else }}
    {{- range $index, $config := .Values.portForwardingList }}
    - port: {{ $config.containerPort }}
      targetPort: {{ $config.containerPort }}
      protocol: {{ $config.protocol }}
      name: ix-{{ $.Release.Name }}-{{ $config.nodePort }}-{{ $index }}
    {{- end }}
{{- end }}
  selector:
    {{- include "ix-chart.selectorLabels" . | nindent 4 }}
{{- end }}
